# credits by zeinzo (F I Z I - MEKIPRES)
# @zeinproject
# MUKA LO KAYA KONTOL

from platform import uname
from time import sleep

from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================


@register(outgoing=True, pattern="^.basi(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**TOLOL BAT SIH ANJG LU TYPING SOBAT KEREN BEGITU MANA TYPNG KOSA KATA BASI BAT BASI KEK MEMEK MAKLU YANG UDAH BASI KESERINGAN DIEWE AMA BAPAK BAPAK KOMPLEK DIGILIR DIMASUKIN PIPA PARALON KALO GAK BAMBU UDAH LEBAR KEK GUA BEGITU CUIH KAGA USAH SOBAT KEREN TOLOL MAKLU NOH DI LUAR NEGERI CUMA JADI KACUNG YANG KERJAANNYA CUMA BERSIH BERSIH DAN MALAH KERJANYA KAGA PERNAH BENER EH MAKLU DENGAN SIFAT BINALNYA NGEGODA MAJIKAN BIAR DIEWE BIAR TAMBAH GAJI BUKANNYA GAJINYA NAMBAH MALAH MAKLU NOH DIPECAT KARENA KETAUAN UDAH BUNTING EH PULANG PULANG BAPAK LU LIAT NYA LANGSUNG JANTUNGAN KENA STROKE KARENA BAPAK LU KENA PENYAKIT KOMPLIKASI YAELAH NAJIS CUIH BAPAK LU HIDUP NYA CUMA REBAHAN SABAN HARI BOKER KENCING MAKAN DIKASUR MANA DICEBOKIN MAKE AIR LIUR KARENA SAKING MISKIN NYA KELUARGA LU AIR AJA KAGA MAMPU TOLOL SADAR DIRI BEGO KELUARGA LU AJA UDAH DIUSIR SAMA WARGA KARENA BAU BAPAK LU UDAH KAGA JELAS NGERACUNIN WARGA MENDING LU BALIK NOH KE HUTAN YE LU BIKIN RUMAH DARI RANTING KAYU ATAP PAKE ALANG ALANG ALAS TIDUR MAKE DAUN PISANG KAGA USAH SOK IYE KALO BAPAK LU AJA BENTAR LAGI MATI KAGA ADA YANG MAU NGUBUR JUGA KARENA PENYAKIT NYA BERBAHAYA DAN JALAN SALAH SATUNYA DIBAKAR DAN MAKLU NGEMIS KERUMAH GUA BIAR DAPET DUIT BUAT BELI BENSIN NAJIS CUIH YE MAKLU NOH DILAMPUERAH OPEN BO BUKANNYA DAPET DUIT MALAH DIGANG BANG ANAK PUNK CUMA DIBAYAR DIAJAKIN MABOK DICIU RAME RAME NAJIS BAT SIH KELUARGA LU TOLOL YE MENDING NIH LU JAN JADI BEBAN KELUARGA TOLOL SADAR DIRI BEGO ADEKLU CUMA BUAT JAJAN AJA AMPE NYEPONGIN KONTOL TETANGGA YAILAH NAJIS CUIH KAGA KEREN KERENNYA KELUARGA LU BEGO YE LU TU ANAK HARAM HASIL GANGBANGAN SUPIR ANGKUTAN YANG HABIS LAHIR DIBUANG KEHUTAN DIASUH AMA MONYET BEKANTAN MANA HIDUP NYA GELANTUNGAN UDAH KEK TARZAN KAGAK TAU ATURAN MUKALU AJA BERANTAKAN MAKANYA NIH MANDI TOLOL HIDUP JAN CUMA NGOTORIN BUMI DOANG YE MENTANG MENTANG DIHUTAN SUSAH AIR MANDI CUMA NUNGGU AIR HUJAN MANA KAGA MAKE SABUN MAKENYA CUMA BATU BUAT GOSOKAN ITUPUN KAGA NGELUNTURIN DAKI LU YANG UDAH 5 CM TEBEL NYA YAILAH MANA MAKE DAUN DAUN DOANG BIAR AGAK WANGIAN MUKA LU NOH UDAH GRADAGAN BOLONG BOLONG KEK JALAN PEDESAAN MANA BERMINYAK UDAH KEK SPONS CUCI PIRING MANA BAPAK LU KIKIR BAT KEK TUAN KEK IDUNG LU UDAH GEDE KEK SQUIDWARD KARENA PENYAKIT POLIP EH KONTOL UDAH KECIL KEK PLANTOK MANA LEBIH KECIL LAGI UDAH KEK CACING PITA NAJIS CUIH MANA CUMA JADI PARASIT DOANG IDUP LU NAJIS**"
    )


@register(outgoing=True, pattern="^.km(?: |$)(.*)")
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit(
        "**YAELAH BOCAH BOCAH KEK ELU NIH YA GA PANTES PISAN TOLOL MAEN DI TELE, KARENA APA? KARENA ELU ITU JELEK GITU YAKAN, UDAH JELEK MISKIN PULA. TERUS TERUS BAPANYA NGULI ANAKNYA MABOK GITU NAJIS, KAGA ADA KASIAN KASIANNYA TOLOL. BAPA LU TUH NGULI KIRENGAT NYA SAMPE KE BOOL BOOL TOLOL, EH ANAKNYA MALAH JADI ORANG TOLOL GITU KAN\nNIH BEGO GUA KASIH SARAN SAMA ELU NIH YEE. MAKNNYA TOLOL KALAU JELEK, ITEM, BULUK SAMA MISKIN DIEM AJ TOLOL GAUSAH SO SO BELAGU GITU KAN LAWAN GUA. GUA SO PASTI TAU, GALAMA JUGA ELU UDAH KEMPES TUH TYPINGAN. JADI TIPIS YAKAN KARENA APA? KARENA ELU GAPUNYA KOSA KATA DAN JUGA ELU ITU GA PUNYA OTAK TOLOL, JADI TIPIS TIPIS. BOCAH BOCAH AMPAS KE ELU NIH YA GUA NGETIK SAMBIL MEREM JUGA BISA TOLOL LAWA ELU MAH EZZ BANGET GITU\nUDAH SEGITU DOANG? GADA DAMAGE DAMAGE NYA AJG TYPINGAN LU TIPIS TIPIS BANGET ADUH, AMPAS LO MAS BEGO GAPUNYA KOSA KATA ABIS ITU SI SO SOAN NYENGGOL. EH PAS UDAH WAR LO NYA CUPU, ADUHHH UDAH GA ABIS PIKIE GUA SAMA BOCAH TOLOL KE ELU GITU KAN AJG.**"

    )


CMD_HELP.update(
    {
        "war3": "**Modules** - `war3`\
        \n\n Cmd : `.basi`\
        \nUsage : coba aja sendiri\
        \n\n Cmd : `.km`\
        \nUsage : coba aja sendiri\
    "
    }
)
